### ISSUE TITLE
Add device and driver bindings?

### ISSUE THREAD

**Issue by dirkbehme** [tgross35/RFL-patch-registry#1]
Do we want to add

https://github.com/YakoYakoYokuYoku/linux/commits/driver-rust

here?

See

https://rust-for-linux.zulipchat.com/#narrow/stream/288089-General/topic/Platform.20device.20and.20devicetree.20abstraction.3F/near/403857994

for the discussion about it.

**Comment by tgross35** [comment]
Thanks for the link, added!
