### ISSUE TITLE
Bindings for debugs, devices, driver, platform, file, io_pgtable and of/devicetree

### ISSUE THREAD

**Issue by dirkbehme** [tgross35/RFL-patch-registry#3]
Just fyi: In

https://github.com/Fabo/linux/commits/fparent/rust-i2c
https://github.com/Fabo/linux/commits/fparent/rust-debugfs

Fabien Parent has experimental bindings for
* File operations
* Debugfs
* io_pgtable
* devices
* driver
* platform
* of/devicetree
against more or less recent rust-dev (6.7.0-rc1). At least they seem to build nicely on top of recent rust-dev.

Just wanted to mention that here in case it might be interesting.

**Comment by tgross35** [comment]
Awesome, thanks! I'd take a PR to add these if you want, or I can do it myself at some point

**Comment by dirkbehme** [comment]
>  I'd take a PR to add these if you want, or I can do it myself at some point

I might be wrong, but I'm under the impression that at least for devices/driver we have different sources from different people for different RFL base versions (6.3, 6.6, 6.7-rc1) with maybe different functionality. For example, I'm under the impression that we added a different flavor of devices/driver yesterday, already. So I'm slightly unclear how to handle that.

**Comment by dirkbehme** [comment]
* sysfs (nearly one year old, but could be a starting point)

https://github.com/YakoYakoYokuYoku/linux/commits/sysfs-support

* regmap (work in progress)

https://github.com/Fabo/linux/commits/fparent/rust-regmap-dev

**Comment by tgross35** [comment]
Thanks for the links. It looks like some of what you mentioned (e.g. io_pgtable) were applied from other trees, so I tried to link the upstream.

I also added a column for the merge base, which is pretty rough but at least gives an idea.

I'll close this, feel free to open more issues or PRs if anything needs an update.
